#!/usr/bin/env sh

LOCAL_HOST="${LOCAL_HOST:-192.168.0.160}"
HYDRA_PUBLIC_URL="${HYDRA_PUBLIC_URL:-http://$LOCAL_HOST:4444}"
HYDRA_ADMIN_URL="${HYDRA_ADMIN_URL:-http://127.0.0.1:4445}"
CONSENT_NODE_URL="${CONSENT_NODE_URL:-http://$LOCAL_HOST:3000}"
CALLBACK_URL="${CALLBACK_URL:-http://$LOCAL_HOST:5555}"
EXPRESS_LOGIN_URL="${EXPRESS_LOGIN_URL:-http://$LOCAL_HOST:5560}"
CLIENT_ID="${CLIENT_ID:-verus-local-client}"
CLIENT_SECRET="${CLIENT_SECRET:-verus-local-secret}"
REDIRECT_URI="${REDIRECT_URI:-$CALLBACK_URL/callback}"
EXPRESS_LOGIN_CLIENT_ID="${EXPRESS_LOGIN_CLIENT_ID:-verus-express-login}"
EXPRESS_LOGIN_CLIENT_SECRET="${EXPRESS_LOGIN_CLIENT_SECRET:-verus-express-secret}"
EXPRESS_LOGIN_REDIRECT_URI="${EXPRESS_LOGIN_REDIRECT_URI:-$EXPRESS_LOGIN_URL/callback}"
SCOPES="${SCOPES:-openid offline verusid}"

export LOCAL_HOST HYDRA_PUBLIC_URL HYDRA_ADMIN_URL CONSENT_NODE_URL CALLBACK_URL EXPRESS_LOGIN_URL
export CLIENT_ID CLIENT_SECRET REDIRECT_URI EXPRESS_LOGIN_CLIENT_ID EXPRESS_LOGIN_CLIENT_SECRET EXPRESS_LOGIN_REDIRECT_URI SCOPES
